apiVersion: v1
name: cloud-native-workstation
version: 0.1.1
dependencies:
- name: tensorflow-notebook
  version: 0.1.3
  repository: https://kubernetes-charts.storage.googleapis.com
- name: hackmd
  version: 1.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
