apiVersion: v1
name: cloud-native-workstation
version: 1.0.0
dependencies:
- name: hackmd
  version: 1.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: components.hackmd.enabled
- name: selenium
  version: 1.0.10
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: components.selenium.enabled