user: workstation
passwd: M@inz!
components:
  code:
    enabled: true
  hackmd:
    enabled: false
  kdenlive:
    enabled: false
  selenium:
    enabled: false
  jupyter:
    enabled: false
access:
- name: keycloak
  port: 8080
- name: code
  port: 3000
- name: hugo
  port: 1313
- name: hackmd
  port: 3003
- name: kdenlive-desktop
  port: 6901
- name: kdenlive-audio
  port: 8090
- name: selenium
  port: 4444
- name: chrome
  port: 6080
- name: jupyter
  port: 8888
hackmd:
  persistence:
    size: 64Gi
  postgresql:
    postgresPassword: M@inz!
selenium:
  hub:
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  chromeDebug:
    enabled: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    extraEnvs:
    - name: VNC_NO_PASSWORD
      value: "1"