user: workstation
passwd: M@inz!
components:
  code:
    enabled: true
  tensorflow:
    enabled: false
  hackmd:
    enabled: true
  kdenlive:
    enabled: false
  selenium:
    enabled: false
access:
- name: keycloak
  port: 8080
- name: code
  port: 3000
- name: hugo
  port: 1313
- name: tensorflow
  port: 8888
- name: tensorboard
  port: 6006
- name: hackmd
  port: 3003
- name: kdenlive-desktop
  port: 6901
- name: kdenlive-audio
  port: 8090
- name: selenium
  port: 4444
- name: chrome
  port: 6080
hackmd:
  persistence:
    size: 64Gi
  postgresql:
    postgresPassword: M@inz!
tensorflow-notebook:
  jupyter:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
    password: M@inz!
  tensorboard:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
  service:
    type: ClusterIP
selenium:
  hub:
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  chromeDebug:
    enabled: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    extraEnvs:
    - name: VNC_NO_PASSWORD
      value: "1"