components:
- name: keycloak
  enabled: true
  port: 8080
- name: theia
  enabled: true
  port: 3000
- name: hugo
  enabled: true
  port: 1313
- name: tensorflow
  enabled: true
  port: 8888
- name: tensorboard
  enabled: true
  port: 6006
- name: hackmd
  enabled: true
  port: 3003
hackmd:
  persistence:
    size: 64Gi
tensorflow-notebook:
  jupyter:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
  tensorboard:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
  service:
    type: ClusterIP
