components:
  code:
    enabled: true
  tensorflow:
    enabled: false
  hackmd:
    enabled: true
  kdenlive:
    enabled: false
access:
- name: keycloak
  port: 8080
- name: code
  port: 3000
- name: hugo
  port: 1313
- name: tensorflow
  port: 8888
- name: tensorboard
  port: 6006
- name: hackmd
  port: 3003
- name: kdenlive-desktop
  port: 6901
- name: kdenlive-audio
  port: 8090
hackmd:
  persistence:
    size: 64Gi
tensorflow-notebook:
  jupyter:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
  tensorboard:
    image:
      repository: tensorflow/tensorflow
      tag: 1.6.0-devel
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
  service:
    type: ClusterIP
